--- 
config:
  - playbook:
      location: /home/runtest.yml 
      params: "version=3.7"
  - script: 
      location: /home/runtest.sh
      params: "test=1"
infra: 
  cloud:
  - type: aws
    count: 4
  - type: openstack  
    count: 2
  baremetal:
    - type: duffy
      count: 5
    - type: beaker
      count: 2
  container:
      count: 3
      name: mysql
      type: docker
logging: 
  format: plaintext
  level: 3
reporting:
  - datahub:
  - resultsDB:
testing:
  - playbook:
      location: /home/runtest.yml 
      params: "version=3.7"
      output:
       - format: xUnit
  - script: 
      location: /home/runtest.sh
      params: "test=1"
      output:
       - format: none
